# Generated by Django 3.2.3 on 2021-05-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teching',
            old_name='course_id',
            new_name='Course_id',
        ),
    ]
