# Generated by Django 3.2.3 on 2021-05-27 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.FloatField(blank=True, default=0, null=True)),
                ('assignment', models.FloatField(blank=True, default=0, null=True)),
                ('midterm', models.FloatField(blank=True, default=0, null=True)),
                ('practical', models.FloatField(blank=True, default=0, null=True)),
                ('final', models.CharField(blank=True, max_length=10, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollments.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollments.student')),
            ],
        ),
    ]
