# Generated by Django 3.2.3 on 2021-05-21 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20210516_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formmodel',
            options={'ordering': ['done', '-date'], 'verbose_name': 'Ticket'},
        ),
    ]
