# Generated by Django 3.2.3 on 2021-05-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_alter_formmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.BooleanField(default=True, verbose_name='Student ?'),
        ),
    ]
