# Generated by Django 3.2.3 on 2021-05-21 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['user_type']},
        ),
    ]
